### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by sishbi** [thiswallz/mat-number-spinner#2]
Hi,
I would like to use this component in my product but it is missing the content for the LICENSE.md
GitHub states that this component is MIT licensed, is that true?
Please fill in some details... 
Thanks, Simon.

**Comment by thiswallz** [comment]
Sorry for the delay, I will update the repo today, it’s completely free and open source

**Comment by sishbi** [comment]
Thank you very much!

**Comment by thiswallz** [comment]
done!, thanks

**Comment by sishbi** [comment]
Thanks.
